INSERT INTO public."JobCategories" ("Id", "Title")
VALUES
	(gen_random_uuid(), 'Administration & Business Support'),
	(gen_random_uuid(), 'Architecture & Engineering'),
	(gen_random_uuid(), 'Arts, Media & Communications'),
	(gen_random_uuid(), 'Customer Service & Sales'),
	(gen_random_uuid(), 'Education & Training'),
	(gen_random_uuid(), 'Finance & Accounting'),
	(gen_random_uuid(), 'Government & Public Administration'),
	(gen_random_uuid(), 'Healthcare'),
	(gen_random_uuid(), 'Human Resources & Recruitment'),
	(gen_random_uuid(), 'Legal'),
	(gen_random_uuid(), 'Manufacturing & Production'),
	(gen_random_uuid(), 'Marketing & Public Relations'),
	(gen_random_uuid(), 'Non-Profit & Social Services'),
	(gen_random_uuid(), 'Retail & Wholesale Trade'),
	(gen_random_uuid(), 'Science & Research'),
	(gen_random_uuid(), 'Security & Law Enforcement'),
	(gen_random_uuid(), 'Skilled Trades & Services'),
	(gen_random_uuid(), 'Transportation & Logistics'),
	(gen_random_uuid(), 'IT, Programming'),
	(gen_random_uuid(), 'Service Industry'),
	(gen_random_uuid(), 'Domestic Staff'),
	(gen_random_uuid(), 'Procurement'),
	(gen_random_uuid(), 'Insurance'),
	(gen_random_uuid(), 'Foreign Languages, Translators'),
	(gen_random_uuid(), 'Psychology'),
	(gen_random_uuid(), 'Construction, Repair & Warehouse'),
	(gen_random_uuid(), 'Telecommunication Network'),
	(gen_random_uuid(), 'Courses, Trainings'),
	(gen_random_uuid(), 'Design'),
	(gen_random_uuid(), 'Mass Media, Journalism'),
	(gen_random_uuid(), 'Beauty, Fitness, Sport'),
	(gen_random_uuid(), 'Farms'),
	(gen_random_uuid(), 'Telephone Operators, Call Centers');